data(ekman, package = "smacof")
n <- attr(ekman, "Size")
ekmanRC <- as.vector((1 - ekman) ^ 3)
ekmanR <- as.matrix((1 - ekman) ^ 3)
xold <- apply(matrix(rnorm(28), n, 2), 2, function(x) x - mean(x)) 
