---
title: "FooBar"
author: 
- Jan de Leeuw - University of California Los Angeles
date: '`r paste("Started December 12 2022, Version of",format(Sys.Date(),"%B %d, %Y"))`'
output:
  bookdown::pdf_document2:
    latex_engine: lualatex 
    includes:
      in_header: preamble.tex
    number_sections: yes
  bookdown::html_document2:
    css: preamble.css
    number_sections: yes
graphics: yes
mainfont: Times New Roman
fontsize: 12pt
bibliography: ["mypubs.bib","total.bib"]
abstract: TBD
---


```{r load code, echo = FALSE}
library(MASS)
source("janUtil.R")
```

# weights

```{r weights, echo = FALSE}
weights <- matrix(c(0, 1, 2, 3, 1, 0, 4, 5, 2, 4, 0, 6, 3, 5, 6, 0), 4, 4)
mPrint(weights)
```

# normalized weights

```{r nweights, echo = FALSE}
weights <- 2 * weights / sum(weights)
mPrint(weights)
```

# delta

```{r delta, echo = FALSE}
delta <- matrix(c(0, 1, 2, 3, 1, 0, 4, 5, 2, 4, 0, 6, 3, 5, 6, 0), 4, 4)
mPrint(delta)
```

# normalized delta

```{r ndelta, echo = FALSE}
delta <- sqrt(2) * delta / sqrt(sum(weights * delta ^ 2))
mPrint(delta)
```

# v

```{r vmat, echo = FALSE}
v <- -weights
diag(v) <- -rowSums(v)
mPrint(v)
```

# vinv

```{r vinv, echo = FALSE}
vinv <- ginv(v)
mPrint(vinv)
```

# xold

```{r xold, echo = FALSE}
xold <- matrix(c(1:4, 4:1), 4, 2)
mPrint(xold)
```

# cross

```{r cross, echo = FALSE}
dd <- delta ^ 2
rd <- rowSums(dd) / 4
rr <- sum(dd) / 16
cross <- -.5 * (dd - outer(rd, rd, "+") + rr)
mPrint(cross)
```

# xold from eigen

```{r xoldnew, echo = FALSE}
e <- eigen(cross)
xold <- e$vectors[, 1:2] %*% diag(sqrt(e$values[1:2]))
mPrint(xold)
```

# dold

```{r dold, echo = FALSE}
dold <- as.matrix(dist(xold))
mPrint(dold)
```

# scaled xold

```{r scold, echo = FALSE}
lbd <- sum(weights * delta * dold) / sum(weights * (dold^ 2))
xold <- lbd * xold
mPrint(xold)
```

# scaled dold

```{r scdold, echo = FALSE}
dold <- lbd * dold
mPrint(dold)
```

# sold

```{r sold, echo = FALSE}
sold <- sum(weights * (delta - dold) ^ 2) / 4.0
mPrint(sold)
```

# guttman transform

```{r guttman, echo = FALSE}
b <- -weights * delta / (dold + diag(4))
diag(b) <- -rowSums(b)
xnew <- vinv %*% b %*% xold
mPrint(xnew)
```