library("microbenchmark")
source("../rcode/smacofR.R")
source("../rcode/smacofRC.R")
source("../timing/timer.R")

print("EKMAN", quote = FALSE)
source("../data/ekman.R")
timer(ekmanR, ekmanRC)
print("MORSE", quote = FALSE)
source("../data/morse.R")
timer(morseR, morseRC)
print("AIRLINE", quote = FALSE)
source("../data/airline.R")
timer(airlineR, airlineRC)
print("WISH", quote = FALSE)
source("../data/wish.R")
timer(wishR, wishRC)
print("GRUIJTER", quote = FALSE)
source("../data/gruijter.R")
timer(gruijterR, gruijterRC)
print("EQDIST", quote = FALSE)
source("../data/eqdist.R")
timer(eqdistR, eqdistRC)
