library("microbenchmark")
source("smacofR.R")
source("smacofRC.R")
source("timer.R")

print("EKMAN", quote = FALSE)
source("ekman.R")
timer(ekmanR, ekmanRC)
print("MORSE", quote = FALSE)
source("morse.R")
timer(morseR, morseRC)
print("AIRLINE", quote = FALSE)
source("airline.R")
timer(airlineR, airlineRC)
print("WISH", quote = FALSE)
source("wish.R")
timer(wishR, wishRC)
print("GRUIJTER", quote = FALSE)
source("gruijter.R")
timer(gruijterR, gruijterRC)
print("EQDIST", quote = FALSE)
source("eqdist.R")
timer(eqdistR, eqdistRC)
